#!/bin/bash
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset012_M12/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset012_M12/pred_test -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset012_M12/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  

# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset012_M12/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset012_M12/pred_test -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset012_M12/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  --save_probabilities
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset014_M1/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset014_M1/pred_test -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset014_M1/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  #--save_probabilities
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset004_D8CT/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset004_D8CT/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset004_D8CT/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4  -chk checkpoint_best.pth #--save_probabilities
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset014_M1/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset014_M1/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset014_M1/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset015_M12/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset015_M12/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset015_M12/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities

# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset011_M1/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset011_M1/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset011_M1/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset012_M12/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset012_M12/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset012_M12/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities

#cascade
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset018_M12_mask/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset018_M12_mask/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset018_M12_mask/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 -chk checkpoint_best.pth  #5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities
# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset017_M1_mask/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset017_M1_mask/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset017_M1_mask/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities

# nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset010_D8/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset010_D8/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset010_D8/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7 8 9  -chk checkpoint_best.pth #--save_probabilities
nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset016_D8CT_mask/imagesTs -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset016_D8CT_mask/pred_test_best -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset016_D8CT_mask/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f 0 1 2 3 4 5 6 7  -chk checkpoint_best.pth #--save_probabilities

