#!/bin/bash
for i in 0 1 2 3 4 5 6 7 8 9
do
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset001_D8/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset001_D8/val_data/fold_$i/prediction/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset001_D8/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset011_M1/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset011_M1/val_data/fold_$i/prediction_600/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset011_M1/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset004_D8CT/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset004_D8CT/val_data/fold_$i/prediction_200/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset004_D8CT/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset014_M1/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset014_M1/val_data/fold_$i/prediction_1000/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset014_M1/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset015_M12/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset015_M12/val_data/fold_$i/prediction_1000/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset015_M12/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset004_D8CT/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset004_D8CT/val_data/fold_$i/prediction_1000/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset004_D8CT/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset011_M1/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset011_M1/val_data/fold_$i/prediction_600_best/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset011_M1/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
#  nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset017_M1_mask/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset017_M1_mask/val_data/fold_$i/prediction_1000_best/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset017_M1_mask/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth
 nnUNetv2_predict_from_modelfolder -i /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset010_D8/val_data/fold_$i/imagesTr/ -o /beegfs/azanella/data_challenge/nnUNet/nnUNet_raw/training/Dataset010_D8/val_data/fold_$i/prediction_600_best/ -m /beegfs/azanella/data_challenge/nnUNet/nnUNet_results/Dataset010_D8/nnUNetTrainer__nnUNetPlans__3d_fullres/ -f $i --save_probabilities -chk checkpoint_best.pth

done